---
title: "Practica3"
author: "Marc Carbonès, Gerald Nilton, Victor Comas"
date: "2025-01-21"
output: html_document
---
# Librerías necesarias
```{r}
if (!require(readr)) install.packages("readr")
if (!require(stringr)) install.packages("stringr")
if (!require(dplyr)) install.packages("dplyr")
if (!require(tidyr)) install.packages("tidyr")

```


# Exercici 1

```{r}
# Cargamos el data frame con los datos.
library(readr)
library(dplyr)

# Cargamos los datos en crudo:
datos_crudos <- read_table("epa-http.csv", col_names = FALSE)

# Con la siguiente variable vamos a hacer una limpieza de los datos:
datos <- datos_crudos

# Renombramos las columnas para que sea más inteligible
colnames(datos) <- c("fuente", "tiempo", "tipo", "url", "protocolo", "status", "bytes")

# Quitamos las comillas dobles que tienen dos de las columnas.
datos$tipo <- gsub('^"', '', datos$tipo)
datos$protocolo <- gsub('"$', '', datos$protocolo)

# Quitamos los claudátors que hay en la columna "tiempo".
datos$tiempo <- gsub('^\\[', '', datos$tiempo)
datos$tiempo <- gsub('\\]$', '', datos$tiempo)
```

# Exercici 2
```{r}

```


# Exercici 3
```{r}
library(tidyr)

# Montamos la columna tiempo en formato de datos elegantes.
# Primero separamos por tipo:
datos <- datos %>%
  separate(tiempo, into = c("dia", "hora", "minuto", "segundo"), sep = ":", convert = TRUE)

# Ahora, suponiendo que los días corresponden a enero de 2025, lo ponemos en formato elegante.
datos$fecha_hora <- as.POSIXct(
  paste("2025-01", datos$dia, datos$hora, datos$minuto, datos$segundo, sep = "-"),
  format = "%Y-%m-%d-%H-%M-%S"
)

# Eliminamos las columnas que nos sobran.
datos <- datos %>% select(-dia, -hora, -minuto, -segundo)

# Movemos la columna otra vez como segunda columna.
datos <- datos[, c("fuente", "fecha_hora", "tipo", "url", "protocolo", "status", "bytes")]

# Categorizamos la columna como fecha. 
as.Date(datos$fecha_hora)

# Reclasificamos a factor las columnas "status", "tipo" y "protocolo", ya que tienen un número limitado de posibles categorías.
datos$status <- factor(datos$status)
datos$tipo <- factor(datos$tipo)
datos$protocolo <- factor(datos$protocolo)



```


# Exercici 4
```{r}

```


# Exercici 5
```{r}

```


# Exercici 6
```{r}

```


# Exercici 7
```{r}

```


# Exercici 8
```{r}

```


# Exercici 9
```{r}

```


